title: Application Developers Day, Pune 2022
date: '2022-10-08'
time: 10:00 AM IST
tag: Community
format: In-person
location: Sagitec Solutions Private Limited, Giga Space IT Park Internal Rd, Pune, Ma, IN
description: |-
  We are excited to host another in-person event at Pune.
  Application Developers Day, Pune 2022 is a free community-focused event dedicated to educate and engage members of the technical community.
  📱Get the updates on the App.
  Our event draws upon the expertise of IT Professionals, Users of Technology, Developers, and Solution Architects who come together to share their real-world experiences, lessons learned, best practices, and general knowledge with other like-minded individuals.
  We will be focusing on building enterprise scalable application on Xelence, Zapier, and Microsoft Platforms including .NET, Microsoft 365, Azure, Power Platform, etc.
  ---------------------------------------------

  Agenda:
  ⏰ 09:30 AM to 10:00 AM IST

  Registration

  ---------------------------------------------
  ⏰ 10:00 AM to 10:15 AM IST

  Welcome and Introduction

  by Nanddeep Nachan and Siddharth Vaghasia (Organizers)

  ---------------------------------------------
  ⏰ 10:15 AM to 10:30 AM IST

  Keynote (Part 1): Key Trends in the Application Development

  by Sameer Pise (Director, Sagitec Solutions)

  ---------------------------------------------
  ⏰ 10:30 AM to 10:45 AM IST

  Keynote (Part 2): Key Considerations when developing the Enterprise applications

  by Rachit Arora (Senior Software Architect, Sagitec Solutions)

  ---------------------------------------------
  ⏰ 10:45 AM to 11:45 AM IST

  Session 1: Xelence Forms & Connectors

  by Amol Kalekar (Xelence Technical Architect, Sagitec Solutions)

  ---------------------------------------------
  ⏰ 11:45 AM to 12:30 PM IST

  Session 2: Xelence APM and Reports

  by Sandip Wagh (Platform Architect, Sagitec Solutions)

  ---------------------------------------------
  ⏰ 12:30 PM to 01:30 PM IST

  🍴🍕 Lunch ( Your lunch is on us! )🥤🍴

  ---------------------------------------------
  ⏰ 01:30 PM to 02:15 PM IST

  Session 3: Let's Explore Power Pages

  by Siddharth Vaghasia and Kunj Sangani

  ---------------------------------------------
  ⏰ 02:15 PM to 03:00 PM IST

  Session 4: Bot Development in an easy steps

  by Nanddeep Nachan and Smita Nachan

  ---------------------------------------------
  ⏰ 03:00 PM to 03:30 PM IST

  🎁 🎁 Quiz, Prize distribution, and Closing notes 🎁🎁

  by Smita Nachan and Kunj Sangani (Organizers)

  ---------------------------------------------
  Cool SWAGS to win!

  Answer simple questions to gift yourself a cool Swag!

  Prize 1: boAt Rockerz 510 bluetooth headphone 🎧
  Prize 2: Water Bottle with Temperature Display
  Prize 3: Water Bottle (White)
  Prize 4: Coffee Mug
  Prize 5: Coffee Mug

  Why attend Application Developers Day, Pune 2022?

  Network the peers and foster on-going relationships
  Learn new things on rapid application development
  Share and improve knowledge on Microsoft technologies
  Speak to experts at the event

  See you there!
meetupUrl: https://www.meetup.com/pune-tech-community/events/288451237/
image: /uploads/events/288451237.jpg
