title: Building AI applications with Azure OpenAI and RAG
date: '2024-12-20'
time: 6:30 PM IST
tag: Azure
format: Virtual
location: Online
description: |-
  This session provides the fundamental information about the Azure Open AI Services and the concepts of Retrieval Augmented Generation approach.
  Session demonstrates implementing the RAG approach with Azure AI Search and Azure Open AI in AI Foundry portal for building AI enabled applications backed by custom data.
  How to join?

  Join with MS Teams meeting

  See you there!
meetupUrl: https://www.meetup.com/pune-tech-community/events/305149146/
image: /uploads/events/305149146.jpg
