title: Explore Managed environments in Power Platform
date: '2022-09-03'
time: 6:00 PM IST
tag: Power Platform
format: Virtual
location: Online
description: |-
  Let us explore together the new Microsoft Power Platform admin preview feature - Managed environments.
  This session will cover:

  What is Managed environments?
  Why it is needed?
  How to enable Managed environments?
  List of available features
  How admins get help and automate their daily governance work?

  How to join?

  Join with MS Teams
  🎤 About the Speaker 🎤

  Raja Subramanian is a Microsoft Certified Professional in SharePoint and Certified Azure Solution Architect Expert.

  He is a results-oriented IT professional in architecture, solution design, implementation, configuration, and maintenance utilizing Microsoft Technologies, especially with SharePoint, MS Azure, and Power Platform.
  Connect with Raja:

  LinkedIn
  Blog

  See you there!
meetupUrl: https://www.meetup.com/pune-tech-community/events/287614878/
image: /uploads/events/287614878.jpg
