title: 'Hands-on Workshop: Building Azure AI Applications in the cloud and locally'
date: '2024-10-09'
time: 6:00 PM IST
tag: Azure
format: In-person
location: Deqode, Viman Nagar, Pune, Lalwani House, Sakore Nagar Rd, Viman Nagar, Pune, IN
description: |-
  We are delighted to announce the Azure AI Hands-on Workshop to be conducted in-person in Pune on Wednesday, October 9, 2024.
  In this In-person hands-on workshop, we will explore how to interact and integrate with multi-modal large language models (LLMs) using Azure AI studio.
  Learn the essentials of interacting with LLMs to handle text, image, and audio inputs. Discover practical workflows for building and deploying AI-driven apps Using VS Code and AI Toolkit locally.
  --------------------------------------------

  📍Location:

  Deqode

  First Floor, Lalwani House,

  Sakore Nagar Rd, Above Axis Bank, Sakore Nagar,

  Viman Nagar, Pune, Maharashtra 411014
  🗺️ Locate on Google map

  --------------------------------------------
  Agenda:

  ⏰ 06:00 PM to 06:15 PM IST

  Registration, Welcome and Introduction to the Workshop

  by Nanddeep Nachan and Siddharth Vaghasia (Organizers)
  ⏰ 06:15 PM to 07:15 PM IST

  Interact with multimodal LLMs and build an ecommerce website from scratch using LLMs using text, images and code-generation capabilities of LLMs

  by Vinayak Hegde (Microsoft)
  ⏰ 07:15 PM to 07:45 PM IST

  Build applications locally using AI toolkit and open source SLMs such

  by Vinayak Hegde (Microsoft)
  ⏰ 07:45 PM to 08:00 PM IST

  Closing notes

  by Smita Nachan and Kunj Sangani (Organizers)
  Whether you're a developer or AI enthusiast, this workshop will equip you with the tools and techniques to harness the power of cloud-based AI while working on your local machine.
  See you there!
  Workshop Pre-requisites

  Attendees should:

  Bring you own laptop
  Preferably carry your own internet connection
  Have basic Azure knowledge
  Have own Azure subscription with Azure OpenAI
  Have installed VS Code (latest version) on laptop.

  Attendees Guidelines

  Kindly take note of the following Visitor Procedures:

  Visitors are allowed subject to verification of the Govt. ID proof.
  Visitors are requested to park their vehicles only at designated parking areas provided.
  All visitors need to obtain “Visitors Badge” at respective building reception and need to be escorted throughout their stay in the premises.
  Visitors should return the temporary visitor pass to the receptionist at the end of their visit.
  Visitors must abide by the "No Photography" & "No Smoking" policies on the premises.
meetupUrl: https://www.meetup.com/pune-tech-community/events/303345681/
image: /uploads/events/303345681.jpg
